### ISSUE TITLE
Question: custom IE returns value in a single value tuple

### ISSUE THREAD

**Issue by IdoDesign** [DeanLight/spannerflow#22]
We have a problem when using custom IEs to differ between functions yielding a single object (int for example), or yielding a single value in a tuple:
```py
def which_century(year):
    yield int(year / 100) + 1

def length(string: str) -> Iterable[int]:
        yield (len(string),)
```

Both of the functions have the same spannerlog out schema: [int] but the return value is different and the way we serialize the data to send back to rust should be different.
I'm not sure I want to add more complex logic to what we have now, so we need to think of a way to handle this situation.

If better solved synchronously we can talk about it tomorrow on our meeting.

**Comment by DeanLight** [comment]
Currently, since it was a hassle to remember to wrap a single output in a tuple, I made it so that if a function in python returns a single value, we wrap it to get a tuple.

This is basically syntactic sugar.

An easy way to fix this, is to take the wrapping if not primitive logic, and apply it either as a decorator or in the python code that does the serialization and deserialisation.

The python should never communicate to the rust a return value that is not a tuple.

**Comment by IdoDesign** [comment]
Got it, missed this  wrapping, it was added only when running the function itself, so I did the same.

Yes, we always send tuples through the api, the problem was in using the function output data for serialization
