### ISSUE TITLE
question: spannerlib relation redefinition  

### ISSUE THREAD

**Issue by techofer** [DeanLight/spannerflow#25]
Hi, 
I came across this issue while running 040_magic_system.ipynb.

as you can see in the screenshot attached, there is redefinition of B.
therefore the engine tries to create the collection B twice, and throws an error as the collection already exists in the second time.

my question is what is the desired behaviour? should I adjust the tests or our code? 
<img width="616" alt="image" src="https://github.com/user-attachments/assets/087d673f-d9e9-4cdb-88c2-18ef2d3a0733">

**Comment by DeanLight** [comment]
Since we expect our users to work inside REPLs like jupyter, we don't want them to have to restart the kernel for every little change, that's why we want to make our Interface idempotent.

This means in this case that if you try to define the same table with the same schema twice, we simply ignore the second time. But if you try to define the same table with a different schema, that might conflict with facts already in that table, and so we should raise an error.
