### ISSUE TITLE
question: schema as function instead of list of types

### ISSUE THREAD

**Issue by techofer** [DeanLight/spannerflow#27]
Hi,
came across this issue while running 030_session.ipynb (spannerlib).

as you can see in the attached screenshot, the string_schema is a function and not a list of types as we expected.
who should run this function and with what input?

<img width="935" alt="image" src="https://github.com/user-attachments/assets/f210d772-fa56-479e-bc85-794a2d119364">

**Comment by DeanLight** [comment]
In cases where an IE function defines a set of functions with different arities (like regexes), instead of a schema you can get  a function of the form `arity:int->schema`. Then this function is used in 2 cases:

* in the parsing of the language, to make sure your rule has correct types given the arities defined in the spannerlog code
* when running the ie function:
  * on the first record on an input table, to verify that the schema matched the expected output (in cases where the given function is for the output schema).
