### ISSUE TITLE
feature: get graph ouput schema - num of fields and their types  

### ISSUE THREAD

**Issue by techofer** [DeanLight/spannerflow#9]

**Comment by IdoDesign** [comment]
Expanding on that:
The generated rust function gets as an argument hash map of vector of vector of strings representing the input data  for each input collection, and returns a vector of strings as output data. We need to add a way to send back to the engine the output schema - number of cols are known but not the type.

On other note, a thought that popped to my head: since we represent values as strings, what happens when we have irrational number(Does this can happen(maybe when using a user defined IE?)

**Comment by DeanLight** [comment]
* We dont represent values as strings. We use all primitives. I thought you used strings just for the mock since it was easier.
* When we use complex types we said we could save them as json, I guess if we have floats in the jsons we can save them as the the floating point representation and pay the floating point error cost.
* Since we know the schema of the input and the output and the IE functions, we can deduce the output schema.

**Comment by techofer** [comment]
We knew only the input types, but i moved it down the graph as node attribute and changed a liitle the engine so it will be known and auto cast
